{
 "title": "Base de Datos",
 "tags": [
  "mysql",
  "db",
  "final"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "MySQL Disponible",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Conexiones MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Conexiones activas"
    }
   ]
  },
  {
   "title": "Ritmo de Consultas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[1m])",
     "legendFormat": "Questions/s"
    }
   ]
  }
 ]
}