{
 "title": "Red y Ataques",
 "tags": [
  "red",
  "ataques",
  "final"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Ataques Activos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(attack_active)" }
   ]
  },
  {
   "title": "Estado por Ataque",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "attack_active", "legendFormat": "{{attack}}" }
   ]
  },
  {
   "title": "Paquetes por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(lab_container_network_tx_packets_total{service=\"atacante\"}[30s])",
     "legendFormat": "Atacante TX pkt/s"
    },
    {
     "expr": "rate(lab_container_network_rx_packets_total{service=\"router\"}[30s])",
     "legendFormat": "Router RX pkt/s"
    },
    {
     "expr": "rate(lab_container_network_rx_packets_total{service=\"web\"}[30s])",
     "legendFormat": "Web RX pkt/s"
    }
   ]
  },
  {
   "title": "NET I/O del Atacante hacia la DMZ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(lab_container_network_tx_bytes_total{service=\"atacante\"}[30s])",
     "legendFormat": "Atacante TX"
    },
    {
     "expr": "rate(lab_container_network_rx_bytes_total{service=\"router\"}[30s])",
     "legendFormat": "Router RX"
    },
    {
     "expr": "rate(lab_container_network_rx_bytes_total{service=\"web\"}[30s])",
     "legendFormat": "Web RX"
    }
   ]
  }
 ]
}