{
 "title": "Servidor Web",
 "tags": [
  "web",
  "apache",
  "final"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU del Contenedor Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "lab_container_cpu_percent{service=\"web\"}",
     "legendFormat": "CPU Web"
    }
   ]
  },
  {
   "title": "Latencia HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_http\",instance=\"http://172.20.10.10/\"}",
     "legendFormat": "Latencia HTTP"
    }
   ]
  },
  {
   "title": "Throughput HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total[1m])",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Conexiones SYN_RECV en el Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lab_container_tcp_syn_recv_connections{service=\"web\"}",
     "legendFormat": "SYN_RECV"
    }
   ]
  }
 ]
}